name: CoverageReport

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cd:
    name: CoverageReport
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        run: |
          CVPKG=$(go list ./... | grep -v mocks | tr '\n' ',')
          go test -coverpkg=${CVPKG} -coverprofile=coverage.out -covermode=count  ./...

      - name: Publish cod cov badge
        run: |
          git clone https://github.com/apageadev/apageadev.github.io
          cd apageadev.github.io
          set -x
          total=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
          if (( $(echo "$total <= 50" | bc -l) )) ; then
            COLOR=red
          elif (( $(echo "$total > 80" | bc -l) )); then
            COLOR=green
          else
            COLOR=orange
          fi
          curl "https://img.shields.io/badge/coavrege-$total%25-$COLOR" > jsontype-coverage-badge.svg
          git add jsontype-coverage-badge.svg
          git commit -m "updating jsontype-coverage-badge"
          git push -u origin main